apiVersion: 1
datasources:
  - name: YMatrix
    uid: ymatrix-dw-demo
    type: postgres
    access: proxy
    url: ymatrix:5432
    user: mxadmin
    database: dw_demo
    isDefault: true
    jsonData:
      database: dw_demo
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: mxadmin123
